version: '2'
services:
  application:
    restart: always
    build: ./web
    ports:
      - "50000:8000"
    links:
      - database:db
    env_file: docker.env
    working_dir: /opt/app
    depends_on:
      - migration
    command: gunicorn --log-config logging.conf -w 2 -b :8000 lost_tracker.main:make_app()

  migration:
    build: ./web
    links:
      - database:db
    env_file: docker.env
    working_dir: /opt/app
    depends_on:
      - database
    command: alembic upgrade head

  database:
    restart: always
    build: ./database
    env_file: docker.env
    ports:
      - "5432"
