name: Pelican

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Embed Secrets
      run: |
        "for f in content/**/*.{rst,md}; do sed -i -e 's/{{GMAPS_API_KEY}}/${{secrets.GMAPS_API_KEY}}/' '${f}'; done"
    - name: Build Pages
      run: |
        pelican content
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: output
        path: output

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: output
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
